#!/usr/bin/env sh
# mitm
# a handy script to intercept and log TCP traffic locally
#
# usage:
#  mitm source_port destination_port
#
# example:
#  intercept TCP traffic to 4001, spy on it,
#  and forward it to port 3000:
#  mitm 4001 3000

socat -v -x TCP-LISTEN:$1 TCP:localhost:$2
